"""add timestamps to supplier and event

Revision ID: fd667ac70a31
Revises: d0437c85fcd0
Create Date: 2026-05-22 10:22:13.977129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fd667ac70a31'
down_revision: Union[str, None] = 'd0437c85fcd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('events', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('events', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('suppliers', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('suppliers', sa.Column('updated_at', sa.DateTime(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'updated_at')
    op.drop_column('suppliers', 'created_at')
    op.drop_column('events', 'updated_at')
    op.drop_column('events', 'created_at')
    # ### end Alembic commands ###
